/**
 * Generates `supabase/seed.sql` from the app's mock data so the database can be
 * populated with the same demo dataset the prototype shipped with.
 *
 *   node scripts/gen-seed.mjs
 *
 * It transpiles the (type-only-importing) mock-data/ward modules to plain JS,
 * imports them, and emits INSERT statements. Column names are converted
 * camelCase → snake_case; jsonb columns keep their nested camelCase shape.
 */
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import ts from "typescript";

const ROOT = process.cwd();

async function loadModule(relPath) {
  const src = readFileSync(join(ROOT, relPath), "utf8");
  const js = ts.transpileModule(src, {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 },
  }).outputText;
  const dir = mkdtempSync(join(tmpdir(), "seed-"));
  const file = join(dir, "mod.mjs");
  writeFileSync(file, js);
  return import(pathToFileURL(file).href);
}

const camelToSnake = (key) => key.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);

function sqlValue(value, isJsonb) {
  if (value === null || value === undefined) return "NULL";
  if (isJsonb) return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Emit one INSERT per row, only for the columns present on that row. */
function insertRows(table, rows, jsonbColumns = []) {
  const jsonb = new Set(jsonbColumns);
  const lines = [`-- ${table}`];
  for (const row of rows) {
    const cols = [];
    const vals = [];
    for (const [key, value] of Object.entries(row)) {
      if (value === undefined) continue;
      const col = camelToSnake(key);
      cols.push(col);
      vals.push(sqlValue(value, jsonb.has(col)));
    }
    lines.push(
      `insert into public.${table} (${cols.join(", ")}) values (${vals.join(", ")}) on conflict (id) do nothing;`,
    );
  }
  return lines.join("\n");
}

const mock = await loadModule("src/lib/mock-data.ts");
const ward = await loadModule("src/lib/ward.ts");

const sections = [];

sections.push(insertRows("bishopric_members", mock.MOCK_BISHOPRIC_MEMBERS));
sections.push(insertRows("members", mock.MOCK_MEMBERS));
sections.push(insertRows("callings", mock.MOCK_CALLINGS, ["suggested_replacements"]));
sections.push(insertRows("meetings", mock.MOCK_MEETINGS, ["agenda", "program"]));
sections.push(insertRows("announcements", mock.MOCK_ANNOUNCEMENTS));
sections.push(insertRows("interviews", mock.MOCK_INTERVIEWS));
sections.push(insertRows("availability_blocks", mock.MOCK_AVAILABILITY));
sections.push(insertRows("availability_exceptions", mock.MOCK_AVAILABILITY_EXCEPTIONS));
sections.push(
  insertRows(
    "roster_groups",
    mock.MOCK_ROSTER.map((g, i) => ({ id: `rg-${i + 1}`, position: i, ...g })),
    ["entries"],
  ),
);
sections.push(insertRows("tasks", mock.MOCK_TASKS, ["context"]));
sections.push(
  insertRows("ward_info", [{ id: "default", ...ward.DEFAULT_WARD_INFO }], ["leadership"]),
);

const header = `-- ============================================================================
-- Open Bishopric — seed data (generated by scripts/gen-seed.mjs)
--
-- Populates ward data with the prototype's demo dataset. Auth users/profiles are
-- NOT seeded here — invite bishopric members via the Supabase dashboard, which
-- creates their profile automatically (see handle_new_user trigger).
-- Run automatically by \`supabase db reset\`, or apply manually with psql.
-- ============================================================================
`;

writeFileSync(join(ROOT, "supabase/seed.sql"), `${header}\n${sections.join("\n\n")}\n`);
console.log("Wrote supabase/seed.sql");
