-- ============================================================================
-- Open Bishopric — access tokens for the MCP server
--
-- The assistant's tools are served over MCP at /api/mcp/<token> so they can be
-- added to Claude as a custom connector. Each token is generated by a signed-in
-- bishopric member in Settings and acts as them. Only a SHA-256 hash is stored;
-- the token itself is shown once, at creation. Deleting a row revokes it, and
-- tokens go away with their user.
--
-- RLS is on with no policies: only the service role (the API routes, after
-- checking the session) can read or write this table.
--
-- Forward-only + idempotent, mirroring prior migrations. Never destructive.
-- ============================================================================

create table if not exists public.mcp_tokens (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  name         text not null,
  token_hash   text not null unique,
  token_hint   text not null,
  created_at   timestamptz not null default now(),
  last_used_at timestamptz
);

create index if not exists mcp_tokens_user_id_idx on public.mcp_tokens (user_id);

alter table public.mcp_tokens enable row level security;
